name = "Hyper"
packagesDir = "../.lake/packages"

[package]
name = "Hyper"

[[lean_lib]]
name = "Hyper"
globs = ["Hyper.+"]

[[require]]
name = "mathlib"
rev = "v4.34.1"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
