import Hyper.ContextIntegral

/-! Exact dart probabilities on the Boolean algebra generated by a diagonal,
one distinguished point on it, and one distinguished point off it.
Contents encode the stated resolution convention. The event algebra, all
normalizations, inequalities, and mixed-denominator conditioning are proved;
this does not postulate a grid of all real points. -/
noncomputable section
open scoped BigOperators AlgebraicHyperreal
namespace AlgebraicDart
open AlgebraicIntegral

abbrev H := RatFunc ℝ
abbrev ω : H := AlgebraicHyperreal.omega
abbrev ε : H := AlgebraicHyperreal.epsilon

private theorem hw : (2 : H) < ω := by
  simpa only [map_ofNat] using AlgebraicHyperreal.constant_lt_omega (2 : ℝ)

/-- Cells: marked diagonal point, remaining diagonal, marked off-diagonal
point, remaining board. Their symbolic counts total ω² exactly. -/
def board : Context H (Fin 4) where
  content := ![1, ω - 1, 1, ω ^ 2 - ω - 1]
  content_nonneg i := by
    fin_cases i
    · change (0 : H) ≤ 1
      exact zero_le_one
    · change (0 : H) ≤ ω - 1
      linarith [hw]
    · change (0 : H) ≤ 1
      exact zero_le_one
    · change (0 : H) ≤ ω ^ 2 - ω - 1
      nlinarith [hw, sq_nonneg (ω - 2)]
  total_pos := by
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, add_zero]
    have h : 0 < ω := lt_trans (by norm_num) hw
    nlinarith [sq_pos_of_pos h]

def point : Finset (Fin 4) := {0}
def diagonal : Finset (Fin 4) := {0, 1}
def offPoint : Finset (Fin 4) := {2}

theorem board_total : board.total = ω ^ 2 := by
  simp [Context.total, board, Fin.sum_univ_succ]

theorem point_probability : board.prob point = ε ^ 2 := by
  rw [point, Context.prob_singleton, board_total]
  simp [board, AlgebraicHyperreal.epsilon]

theorem diagonal_probability : board.prob diagonal = ε := by
  unfold Context.prob Context.integral
  rw [board_total]
  simp [Context.raw, Context.indicator, diagonal, board, Fin.sum_univ_succ]
  unfold ε AlgebraicHyperreal.epsilon
  field_simp [AlgebraicHyperreal.omega_ne_zero]

theorem offPoint_probability : board.prob offPoint = ε ^ 2 := by
  rw [offPoint, Context.prob_singleton, board_total]
  simp [board, AlgebraicHyperreal.epsilon]

theorem point_strictly_rarer : 0 < board.prob point ∧ board.prob point < board.prob diagonal := by
  rw [point_probability, diagonal_probability]
  have h0 := AlgebraicHyperreal.epsilon_pos (K := ℝ)
  have h1 := AlgebraicHyperreal.epsilon_lt_one (K := ℝ)
  constructor
  · exact sq_pos_of_pos h0
  · nlinarith

theorem diagonal_to_point_ratio : board.prob diagonal / board.prob point = ω := by
  rw [point_probability, diagonal_probability]
  unfold ε AlgebraicHyperreal.epsilon
  field_simp [AlgebraicHyperreal.omega_ne_zero]

/-- Exact conditioning on the diagonal: no infinitesimal is discarded. -/
theorem point_given_diagonal :
    board.conditional diagonal (Context.indicator point) = ε := by
  have h : (fun i => Context.indicator diagonal i * Context.indicator point i : Fin 4 → H) =
      Context.indicator point := by
    funext i
    fin_cases i <;> norm_num [Context.indicator, diagonal, point]
  unfold Context.conditional Context.restricted
  rw [h]
  change board.prob point / board.prob diagonal = ε
  rw [point_probability, diagonal_probability]
  field_simp [ne_of_gt (AlgebraicHyperreal.epsilon_pos (K := ℝ))]

theorem mixed_support_probability :
    board.prob (diagonal ∪ offPoint) = ε + ε ^ 2 := by
  have hd : Disjoint diagonal offPoint := by decide
  have h := board.prob_disjoint_union hd
  rw [diagonal_probability, offPoint_probability] at h
  exact h

/-- The old termwise inverse cannot prove this correct mixed-order answer. -/
theorem diagonal_given_mixed :
    board.conditional (diagonal ∪ offPoint) (Context.indicator diagonal) = 1 / (1 + ε) := by
  have h : (fun i => Context.indicator (diagonal ∪ offPoint) i * Context.indicator diagonal i
      : Fin 4 → H) = Context.indicator diagonal := by
    funext i
    fin_cases i <;> norm_num [Context.indicator, diagonal, offPoint]
  unfold Context.conditional Context.restricted
  rw [h]
  change board.prob diagonal / board.prob (diagonal ∪ offPoint) = _
  rw [diagonal_probability, mixed_support_probability]
  have he := AlgebraicHyperreal.epsilon_pos (K := ℝ)
  have hs : ε + ε ^ 2 ≠ 0 := ne_of_gt (add_pos he (sq_pos_of_pos he))
  have ho : 1 + ε ≠ 0 := ne_of_gt (add_pos zero_lt_one he)
  field_simp

theorem point_delta_sifts (f : Fin 4 → H) :
    board.integral (fun i => f i * board.delta point i) = f 0 := by
  apply board.delta_singleton 0
  norm_num [board]

theorem whole_board : board.integral (fun _ => 1) = 1 := board.integral_one

/-- Signed finite differences of an interval indicator distinguish a point
from a patch: a two-cell central stencil is a half/half average. -/
theorem two_cell_stencil (a b : H) :
    (a * (1 / (2 * ε)) * ε + b * (1 / (2 * ε)) * ε) = (a + b) / 2 := by
  field_simp [ne_of_gt (AlgebraicHyperreal.epsilon_pos (K := ℝ))]

#print axioms whole_board
#print axioms point_strictly_rarer
#print axioms diagonal_given_mixed
#print axioms point_delta_sifts
end AlgebraicDart
