import Hyper.GeometricContent

/-! A global, decomposition-independent, strictly positive content on the
one-dimensional interval algebra.

An event is presented as a finite list of pairwise disjoint *cells*, each a
point `{a}` or an open interval `(a,b)` with `a < b`. Every set in the
algebra generated by closed intervals has such a presentation. The content
of a presentation is the sum of its cell contents, `ε` for a point and
`(b-a) - ε` for an open interval.

The main theorem `content_eq_of_set_eq` says that two presentations of the
same set have the same content. The proof writes the content
representation-free as `C (Lebesgue length) + ε * χ`, where `χ` is the
Euler characteristic computed as a finite jump sum
`∑ₓ (1_E(x) - 1_E(x⁺))`. `content_pos` gives strict positivity, and
`closed_content` recovers the calibration `[a,b] ↦ (b-a) + ε`.

No axioms are introduced. The d-dimensional box algebra follows by products
(see `paper/global-content.tex`, Proposition on boxes); that step is not
formalized here.
-/
noncomputable section
open scoped AlgebraicHyperreal
open Classical
namespace IntervalAlgebra
open AlgebraicHyperreal MeasureTheory

abbrev H := RatFunc ℝ
local notation "ε" => epsilon (K := ℝ)
local notation "C" => (RatFunc.C : ℝ →+* H)

/-- A cell of the one-dimensional algebra. -/
inductive Cell
  | pt (a : ℝ)
  | ioo (a b : ℝ)

namespace Cell

def set : Cell → Set ℝ
  | pt a => {a}
  | ioo a b => Set.Ioo a b

def ok : Cell → Prop
  | pt _ => True
  | ioo a b => a < b

def len : Cell → ℝ
  | pt _ => 0
  | ioo a b => b - a

def euler : Cell → ℤ
  | pt _ => 1
  | ioo _ _ => -1

def ends : Cell → Finset ℝ
  | pt a => {a}
  | ioo a b => {a, b}

def content (c : Cell) : H := C c.len + ε * (c.euler : H)

theorem content_pos (c : Cell) (hc : c.ok) : 0 < c.content := by
  cases c with
  | pt a => simpa [content, len, euler] using epsilon_pos (K := ℝ)
  | ioo a b =>
    have h : ε < C (b - a) := epsilon_lt_constant (sub_pos.mpr hc)
    simp only [content, len, euler]
    push_cast
    linarith

theorem measurable (c : Cell) : MeasurableSet c.set := by
  cases c <;> simp [set, measurableSet_Ioo]

theorem volume_eq (c : Cell) (hc : c.ok) :
    volume c.set = ENNReal.ofReal c.len := by
  cases c with
  | pt a => simp [set, len]
  | ioo a b => simp [set, len, Real.volume_Ioo]

theorem len_nonneg (c : Cell) (hc : c.ok) : 0 ≤ c.len := by
  cases c with
  | pt a => simp [len]
  | ioo a b => simpa [len] using (sub_pos.mpr (show a < b from hc)).le

end Cell

/-! ### Right germs and the jump-sum Euler characteristic -/

/-- `E` contains a whole right neighbourhood `(x, x+δ)`. -/
def germ (E : Set ℝ) (x : ℝ) : Prop := ∃ δ > 0, Set.Ioo x (x + δ) ⊆ E

/-- Every right neighbourhood is eventually inside `E` or inside `Eᶜ`. -/
def Tame (E : Set ℝ) : Prop :=
  ∀ x, ∃ δ > 0, Set.Ioo x (x + δ) ⊆ E ∨ Set.Ioo x (x + δ) ⊆ Eᶜ

def ind (E : Set ℝ) (x : ℝ) : ℤ := if x ∈ E then 1 else 0
def gind (E : Set ℝ) (x : ℝ) : ℤ := if germ E x then 1 else 0

/-- Euler characteristic as a finite jump sum over the test points `S`. -/
def chi (S : Finset ℝ) (E : Set ℝ) : ℤ := ∑ x ∈ S, (ind E x - gind E x)

theorem ind_union {A B : Set ℝ} (h : Disjoint A B) (x : ℝ) :
    ind (A ∪ B) x = ind A x + ind B x := by
  unfold ind
  by_cases ha : x ∈ A
  · have hb : x ∉ B := fun hb => Set.disjoint_left.mp h ha hb
    simp [ha, hb]
  · by_cases hb : x ∈ B <;> simp [ha, hb]

private theorem mid_mem {x δ : ℝ} (hδ : 0 < δ) : x + δ / 2 ∈ Set.Ioo x (x + δ) :=
  ⟨by linarith, by linarith⟩

theorem not_germ_of_compl {E : Set ℝ} {x δ : ℝ} (hδ : 0 < δ)
    (h : Set.Ioo x (x + δ) ⊆ Eᶜ) : ¬ germ E x := by
  rintro ⟨δ', hδ', h'⟩
  have hm : x + min δ δ' / 2 ∈ Set.Ioo x (x + min δ δ') := mid_mem (lt_min hδ hδ')
  have h1 : x + min δ δ' / 2 ∈ Set.Ioo x (x + δ) :=
    ⟨hm.1, lt_of_lt_of_le hm.2 (by linarith [min_le_left δ δ'])⟩
  have h2 : x + min δ δ' / 2 ∈ Set.Ioo x (x + δ') :=
    ⟨hm.1, lt_of_lt_of_le hm.2 (by linarith [min_le_right δ δ'])⟩
  exact h h1 (h' h2)

theorem gind_union {A B : Set ℝ} (h : Disjoint A B) (hA : Tame A) (hB : Tame B)
    (x : ℝ) : gind (A ∪ B) x = gind A x + gind B x := by
  unfold gind
  obtain ⟨δa, hδa, ha⟩ := hA x
  obtain ⟨δb, hδb, hb⟩ := hB x
  rcases ha with ha | ha
  · -- A has the germ, hence B does not
    have gA : germ A x := ⟨δa, hδa, ha⟩
    have gU : germ (A ∪ B) x := ⟨δa, hδa, ha.trans Set.subset_union_left⟩
    have nB : ¬ germ B x := by
      apply not_germ_of_compl hδa
      intro y hy hyB
      exact Set.disjoint_left.mp h (ha hy) hyB
    simp [gA, gU, nB]
  · have nA : ¬ germ A x := not_germ_of_compl hδa ha
    rcases hb with hb | hb
    · have gB : germ B x := ⟨δb, hδb, hb⟩
      have gU : germ (A ∪ B) x := ⟨δb, hδb, hb.trans Set.subset_union_right⟩
      simp [nA, gB, gU]
    · have nB : ¬ germ B x := not_germ_of_compl hδb hb
      have nU : ¬ germ (A ∪ B) x := by
        apply not_germ_of_compl (lt_min hδa hδb)
        intro y hy hyU
        have hya : y ∈ Set.Ioo x (x + δa) :=
          ⟨hy.1, lt_of_lt_of_le hy.2 (by linarith [min_le_left δa δb])⟩
        have hyb : y ∈ Set.Ioo x (x + δb) :=
          ⟨hy.1, lt_of_lt_of_le hy.2 (by linarith [min_le_right δa δb])⟩
        rcases hyU with hyA | hyB
        · exact ha hya hyA
        · exact hb hyb hyB
      simp [nA, nB, nU]

theorem chi_union (S : Finset ℝ) {A B : Set ℝ} (h : Disjoint A B)
    (hA : Tame A) (hB : Tame B) : chi S (A ∪ B) = chi S A + chi S B := by
  unfold chi
  rw [← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun x _ => ?_
  rw [ind_union h, gind_union h hA hB]
  ring

theorem tame_union {A B : Set ℝ} (hA : Tame A) (hB : Tame B) : Tame (A ∪ B) := by
  intro x
  obtain ⟨δa, hδa, ha⟩ := hA x
  obtain ⟨δb, hδb, hb⟩ := hB x
  rcases ha with ha | ha
  · exact ⟨δa, hδa, Or.inl (ha.trans Set.subset_union_left)⟩
  rcases hb with hb | hb
  · exact ⟨δb, hδb, Or.inl (hb.trans Set.subset_union_right)⟩
  refine ⟨min δa δb, lt_min hδa hδb, Or.inr ?_⟩
  intro y hy hyU
  have hya : y ∈ Set.Ioo x (x + δa) :=
    ⟨hy.1, lt_of_lt_of_le hy.2 (by linarith [min_le_left δa δb])⟩
  have hyb : y ∈ Set.Ioo x (x + δb) :=
    ⟨hy.1, lt_of_lt_of_le hy.2 (by linarith [min_le_right δa δb])⟩
  rcases hyU with hyA | hyB
  · exact ha hya hyA
  · exact hb hyb hyB

theorem tame_empty : Tame (∅ : Set ℝ) :=
  fun _ => ⟨1, one_pos, Or.inr (by simp)⟩

namespace Cell

theorem tame (c : Cell) : Tame c.set := by
  intro x
  cases c with
  | pt a =>
    by_cases hx : x < a
    · refine ⟨a - x, sub_pos.mpr hx, Or.inr ?_⟩
      intro y hy hya
      simp only [set, Set.mem_singleton_iff] at hya
      subst hya; linarith [hy.2]
    · refine ⟨1, one_pos, Or.inr ?_⟩
      intro y hy hya
      simp only [set, Set.mem_singleton_iff] at hya
      subst hya; linarith [hy.1]
  | ioo a b =>
    by_cases hx : x < a
    · refine ⟨a - x, sub_pos.mpr hx, Or.inr ?_⟩
      intro y hy hyE
      exact absurd hyE.1 (by simp only [set] at *; linarith [hy.2])
    by_cases hxb : x < b
    · refine ⟨b - x, sub_pos.mpr hxb, Or.inl ?_⟩
      intro y hy
      exact ⟨by linarith [hy.1], by linarith [hy.2]⟩
    · refine ⟨1, one_pos, Or.inr ?_⟩
      intro y hy hyE
      exact absurd hyE.2 (by simp only [set] at *; linarith [hy.1])

/-- The jump sum of a single cell is its Euler characteristic, as soon as the
test points contain the cell's endpoints. -/
theorem chi_eq (c : Cell) (hc : c.ok) (S : Finset ℝ) (hS : c.ends ⊆ S) :
    chi S c.set = c.euler := by
  cases c with
  | pt a =>
    have ha : a ∈ S := hS (by simp [ends])
    have hg : ∀ x, ¬ germ ({a} : Set ℝ) x := by
      rintro x ⟨δ, hδ, h⟩
      have h1 := h (mid_mem (x := x) hδ)
      have h2 : x + δ / 4 ∈ Set.Ioo x (x + δ) := ⟨by linarith, by linarith⟩
      have h2' := h h2
      simp only [Set.mem_singleton_iff] at h1 h2'
      linarith
    have : ∀ x ∈ S, ind ({a} : Set ℝ) x - gind {a} x = if x = a then 1 else 0 := by
      intro x _
      by_cases hxa : x = a <;> simp [ind, gind, hg, hxa]
    simp only [chi, set, euler]
    rw [Finset.sum_congr rfl this, Finset.sum_ite_eq' S a (fun _ => (1 : ℤ))]
    simp [ha]
  | ioo a b =>
    have hab : a < b := hc
    have ha : a ∈ S := hS (by simp [ends])
    have key : ∀ x, ind (Set.Ioo a b) x - gind (Set.Ioo a b) x =
        if x = a then -1 else 0 := by
      intro x
      by_cases hxa : x = a
      · subst hxa
        have g : germ (Set.Ioo x b) x := ⟨b - x, sub_pos.mpr hab, by
          intro y hy; exact ⟨hy.1, by linarith [hy.2]⟩⟩
        simp [ind, gind, g]
      rcases lt_or_gt_of_ne hxa with hlt | hgt
      · have hn : x ∉ Set.Ioo a b := fun h => by linarith [h.1]
        have g : ¬ germ (Set.Ioo a b) x :=
          not_germ_of_compl (sub_pos.mpr hlt) (by
            intro y hy hyE; linarith [hyE.1, hy.2])
        simp [ind, gind, hn, g, hxa]
      · by_cases hxb : x < b
        · have hm : x ∈ Set.Ioo a b := ⟨hgt, hxb⟩
          have g : germ (Set.Ioo a b) x := ⟨b - x, sub_pos.mpr hxb, by
            intro y hy; exact ⟨by linarith [hy.1], by linarith [hy.2]⟩⟩
          simp [ind, gind, hm, g, hxa]
        · have hn : x ∉ Set.Ioo a b := fun h => hxb h.2
          have g : ¬ germ (Set.Ioo a b) x :=
            not_germ_of_compl one_pos (by
              intro y hy hyE; linarith [hyE.2, hy.1, not_lt.mp hxb])
          simp [ind, gind, hn, g, hxa]
    simp only [chi, set, euler]
    rw [Finset.sum_congr rfl (fun x _ => key x),
      Finset.sum_ite_eq' S a (fun _ => (-1 : ℤ))]
    simp [ha]

end Cell

/-! ### Presentations -/

def uset : List Cell → Set ℝ
  | [] => ∅
  | c :: L => c.set ∪ uset L

/-- Pairwise disjointness, stated recursively. -/
def Disj : List Cell → Prop
  | [] => True
  | c :: L => Disjoint c.set (uset L) ∧ Disj L

def AllOk (L : List Cell) : Prop := ∀ c ∈ L, c.ok

def lenSum : List Cell → ℝ
  | [] => 0
  | c :: L => c.len + lenSum L

def eulerSum : List Cell → ℤ
  | [] => 0
  | c :: L => c.euler + eulerSum L

def content : List Cell → H
  | [] => 0
  | c :: L => c.content + content L

def endsAll : List Cell → Finset ℝ
  | [] => ∅
  | c :: L => c.ends ∪ endsAll L

theorem tame_uset : ∀ L : List Cell, Tame (uset L)
  | [] => tame_empty
  | c :: L => tame_union c.tame (tame_uset L)

theorem measurable_uset : ∀ L : List Cell, MeasurableSet (uset L)
  | [] => MeasurableSet.empty
  | c :: L => c.measurable.union (measurable_uset L)

theorem content_split : ∀ L : List Cell,
    content L = C (lenSum L) + ε * (eulerSum L : H)
  | [] => by simp [content, lenSum, eulerSum]
  | c :: L => by
    simp only [content, lenSum, eulerSum, Cell.content, content_split L, map_add]
    push_cast
    ring

theorem lenSum_nonneg : ∀ L : List Cell, AllOk L → 0 ≤ lenSum L
  | [] , _ => le_rfl
  | c :: L, h => add_nonneg (c.len_nonneg (h c (by simp)))
      (lenSum_nonneg L fun d hd => h d (by simp [hd]))

/-- The length part is the Lebesgue measure of the union. -/
theorem volume_uset : ∀ L : List Cell, AllOk L → Disj L →
    volume (uset L) = ENNReal.ofReal (lenSum L)
  | [], _, _ => by simp [uset, lenSum]
  | c :: L, hok, hd => by
    have hokL : AllOk L := fun d hd' => hok d (by simp [hd'])
    simp only [uset, lenSum]
    rw [measure_union hd.1 (measurable_uset L), c.volume_eq (hok c (by simp)),
      volume_uset L hokL hd.2,
      ENNReal.ofReal_add (c.len_nonneg (hok c (by simp))) (lenSum_nonneg L hokL)]

/-- The Euler part is the jump sum of the union. -/
theorem chi_uset (S : Finset ℝ) : ∀ L : List Cell, AllOk L → Disj L →
    endsAll L ⊆ S → chi S (uset L) = eulerSum L
  | [], _, _, _ => by
    simp only [chi, uset, eulerSum, ind, gind, germ, Set.mem_empty_iff_false,
      Set.subset_empty_iff, if_false]
    refine Finset.sum_eq_zero fun x _ => ?_
    have : ¬ ∃ δ > 0, Set.Ioo x (x + δ) = (∅ : Set ℝ) := by
      rintro ⟨δ, hδ, h⟩
      have hm := mid_mem (x := x) hδ
      rw [h] at hm
      exact hm
    simp [this]
  | c :: L, hok, hd, hS => by
    have hokL : AllOk L := fun d hd' => hok d (by simp [hd'])
    have hSc : c.ends ⊆ S := fun x hx => hS (by simp [endsAll, hx])
    have hSL : endsAll L ⊆ S := fun x hx => hS (by simp [endsAll, hx])
    simp only [uset, eulerSum]
    rw [chi_union S hd.1 c.tame (tame_uset L), c.chi_eq (hok c (by simp)) S hSc,
      chi_uset S L hokL hd.2 hSL]

/-- **Independence of decomposition.** Two presentations of the same set
have the same content. -/
theorem content_eq_of_set_eq (L₁ L₂ : List Cell)
    (ok₁ : AllOk L₁) (d₁ : Disj L₁) (ok₂ : AllOk L₂) (d₂ : Disj L₂)
    (hset : uset L₁ = uset L₂) : content L₁ = content L₂ := by
  have hlen : lenSum L₁ = lenSum L₂ := by
    have h := congrArg (fun s => (volume s).toReal) hset
    simp only [volume_uset L₁ ok₁ d₁, volume_uset L₂ ok₂ d₂] at h
    rwa [ENNReal.toReal_ofReal (lenSum_nonneg L₁ ok₁),
      ENNReal.toReal_ofReal (lenSum_nonneg L₂ ok₂)] at h
  have heul : eulerSum L₁ = eulerSum L₂ := by
    set S := endsAll L₁ ∪ endsAll L₂
    rw [← chi_uset S L₁ ok₁ d₁ Finset.subset_union_left,
      ← chi_uset S L₂ ok₂ d₂ Finset.subset_union_right, hset]
  rw [content_split, content_split, hlen, heul]

/-- **Strict positivity.** Every nonempty presentation has positive content. -/
theorem content_pos : ∀ L : List Cell, AllOk L → L ≠ [] → 0 < content L
  | [], _, h => absurd rfl h
  | [c], hok, _ => by
    simpa [content] using c.content_pos (hok c (by simp))
  | c :: d :: L, hok, _ => by
    have h1 := c.content_pos (hok c (by simp))
    have h2 := content_pos (d :: L) (fun e he => hok e (by simp_all)) (by simp)
    simp only [content] at h2 ⊢
    linarith

/-- Calibration: the closed interval `[a,b]`, presented as two points and an
open interval, has content `(b - a) + ε`. -/
theorem closed_content (a b : ℝ) :
    content [Cell.pt a, Cell.ioo a b, Cell.pt b] = C (b - a) + ε := by
  simp only [content, Cell.content, Cell.len, Cell.euler, map_zero]
  push_cast
  ring

theorem closed_set {a b : ℝ} (h : a < b) :
    uset [Cell.pt a, Cell.ioo a b, Cell.pt b] = Set.Icc a b := by
  ext x
  simp only [uset, Cell.set, Set.mem_union, Set.mem_singleton_iff, Set.mem_Ioo,
    Set.mem_empty_iff_false, or_false, Set.mem_Icc]
  constructor
  · rintro (rfl | ⟨h1, h2⟩ | rfl) <;> constructor <;> linarith
  · rintro ⟨h1, h2⟩
    rcases h1.lt_or_eq with h1 | rfl
    · rcases h2.lt_or_eq with h2 | rfl
      · exact Or.inr (Or.inl ⟨h1, h2⟩)
      · exact Or.inr (Or.inr rfl)
    · exact Or.inl rfl

/-- Two different presentations of `[0,2]`: cut at `1` or not. The theorem
`content_eq_of_set_eq` guarantees that they agree; here we also see it. -/
theorem refinement_example :
    content [Cell.pt 0, Cell.ioo 0 1, Cell.pt 1, Cell.ioo 1 2, Cell.pt 2] =
    content [Cell.pt 0, Cell.ioo 0 2, Cell.pt 2] := by
  have h2 : C (2 - 0 : ℝ) = C (1 - 0) + C (2 - 1) := by rw [← map_add]; norm_num
  simp only [content, Cell.content, Cell.len, Cell.euler, map_zero, h2]
  push_cast
  ring

end IntervalAlgebra
